// Export all assessment components for easy importing
export { default as AssessmentResults } from './AssessmentResults';
export { default as ScoreVisualization } from './ScoreVisualization';
export { default as CRMSpecificRecommendations } from './CRMSpecificRecommendations';
export { default as NextStepsSection } from './NextStepsSection';
export { default as CoCreatorProgramOffer } from './CoCreatorProgramOffer';
export { default as ResultsSharing } from './ResultsSharing';
export { default as IndustryBenchmark } from './IndustryBenchmark';
export { default as AutomationOpportunityCard } from './AutomationOpportunityCard';
export { default as ResultsSummaryCard } from './ResultsSummaryCard';
export { default as RecommendationsList } from './RecommendationsList';
export { default as AssessmentFlow } from './AssessmentFlow';
export { default as ProgressIndicator } from './ProgressIndicator';
export { default as QuestionStep } from './QuestionStep';
export { default as CRMSelector } from './CRMSelector';
export { default as ScaleInput } from './ScaleInput';
export { default as MultipleChoiceInput } from './MultipleChoiceInput';
export { default as TextInput } from './TextInput';
export { default as AssessmentModal } from './AssessmentModal';